import os

# MAIN CONFIGS
EBAY_CLIENT_ID = os.getenv("EBAY_CLIENT_ID")
EBAY_CLIENT_SECRET = os.getenv("EBAY_CLIENT_SECRET")
EBAY_REFRESH_TOKEN = os.getenv("EBAY_REFRESH_TOKEN")
REDIRECT_URI = os.getenv("REDIRECT_URI")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

# EBAY CONFIGS
MARKETPLACE_ID = "EBAY_IT"
MERCHANT_LOCATION_KEY = "sezze-warehouse"
FULFILLMENT_POLICY_ID = 294952595011
PAYMENT_POLICY_ID = 294966878011
RETURN_POLICY_ID = 294966928011

# Fulfillment Policies by weight
EBAY_FPOLICY_ID_DEFAULT = 294952595011
EBAY_FPOLICY_ID_LIGHT = os.getenv("EBAY_FPOLICY_ID_LIGHT")  # <= 0.75 kg
EBAY_FPOLICY_ID_MEDIUM = os.getenv("EBAY_FPOLICY_ID_MEDIUM")  # <= 2 kg
EBAY_FPOLICY_ID_HEAVY = os.getenv("EBAY_FPOLICY_ID_HEAVY")  # <= 5 kg
EBAY_FPOLICY_ID_XHEAVY = os.getenv("EBAY_FPOLICY_ID_XHEAVY")  # >  5 kg
